# Generated by Django 4.2.15 on 2024-08-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
