# Generated by Django 4.2.15 on 2024-08-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars\\R.png', null=True, upload_to='avatars/'),
        ),
    ]
