# Generated by Django 5.1 on 2024-08-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_areze'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areze',
        ),
    ]
