# Generated by Django 5.1 on 2024-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_areze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organ', models.CharField(max_length=255)),
                ('location_organ', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('num_personnel', models.IntegerField()),
                ('num_workshifts', models.IntegerField()),
                ('name_response', models.CharField(max_length=155)),
                ('phone_response', models.CharField(max_length=20)),
            ],
        ),
    ]
