# Generated by Django 5.1 on 2024-08-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_areze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesyllabus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coursesyllabusname',
            name='id',
        ),
        migrations.AlterField(
            model_name='coursesyllabus',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.course'),
        ),
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.coursesyllabus'),
        ),
    ]
