# Generated by Django 5.1 on 2024-08-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_coursesyllabus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='syllabus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.coursesyllabus'),
        ),
    ]
