# Generated by Django 4.2.15 on 2024-08-21 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_coursesyllabusname_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesyllabus',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursesyllabus',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
    ]
