# Generated by Django 4.2.15 on 2024-08-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_coursesyllabus_id_alter_coursesyllabus_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesyllabusname',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='coursesyllabusname',
            name='coursesyllabus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.coursesyllabus'),
        ),
        migrations.AddField(
            model_name='coursesyllabusname',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursesyllabus',
            name='description',
            field=models.TextField(),
        ),
    ]
