# Generated by Django 4.2.15 on 2024-08-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_coursesyllabusname_syllabus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='coursesyllabus',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.coursesyllabus'),
        ),
    ]
