# Generated by Django 4.2.15 on 2024-08-21 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_coursesyllabusname_coursesyllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='coursesyllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coursesyllabus'),
        ),
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
