# Generated by Django 4.2.15 on 2024-08-21 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_coursesyllabus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesyllabusname',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='coursesyllabus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.coursesyllabus'),
        ),
    ]
