# Generated by Django 4.2.15 on 2024-08-22 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_coursesyllabusname_cours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabus',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coursesyllabus', to='home.course'),
        ),
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='coursesyllabus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_names', to='home.coursesyllabus'),
        ),
    ]
