# Generated by Django 4.2.15 on 2024-08-22 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_coursesyllabus_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesyllabusname',
            name='cours',
        ),
        migrations.AddField(
            model_name='coursesyllabusname',
            name='crs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crs', to='home.course'),
        ),
        migrations.AlterField(
            model_name='coursesyllabus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='coursesyllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_names', to='home.coursesyllabus'),
        ),
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
