# Generated by Django 4.2.15 on 2024-08-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_comment_comment_content_remove_comment_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='coursesyllabus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_names', to='home.coursesyllabus'),
        ),
    ]
