# Generated by Django 4.2.15 on 2024-08-27 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_coursesyllabusname_crs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesyllabusname',
            name='crs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crs', to='home.course'),
        ),
    ]
