# Generated by Django 4.2.15 on 2024-08-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_coursesyllabusname_coursesyllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='crs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crs', to='home.course'),
        ),
    ]
