# Generated by Django 4.2.15 on 2024-08-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_coursesyllabusname_crs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabusname',
            name='coursesyllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_names', to='home.coursesyllabus'),
        ),
    ]
