# Generated by Django 4.2.15 on 2024-08-27 08:13

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_coursesyllabusname_coursesyllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_course',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[200, 200], upload_to='images/Course'),
        ),
    ]
