# Generated by Django 4.2.15 on 2024-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_course_image_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_course',
            field=models.ImageField(upload_to='images/Course'),
        ),
    ]
