# Generated by Django 4.2.15 on 2024-08-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_replycomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='reply',
            field=models.TextField(default=None),
        ),
    ]
