# Generated by Django 4.2.15 on 2024-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_replycomment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='areze',
            name='saved_from_view',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
